server:
  port: 8089
spring:
  application:
    name: CONSUMER
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  # 指的是建立连接所用的超时时间
  ConnectTimeout: 2000
  # 指的是建立连接后从服务器获取资源的超时时间（即请求处理的超时时间）
  ReadTimeout: 1000

feign:
  feign:
    client:
      config:
        pay-service: # 对服务提供者（优先级高）：填对应服务提供者名称，
          # 对所有提供者(优先级低)：固定"default"
          connectTimeout: 2000 # 连接超时时间单位ms
          readTimeout: 2000  # 读取超时时间单位ms
  circuitbreaker:
    enabled: true
# 开启服务降级
  hystrix:
    enabled: true
